include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: rocm/dev-ubuntu-18.04

# basic tests

test:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - rocm


# special tests

#test:source:llvm9:
#  extends:
#    - .julia:source
#    - .test
#  tags:
#    - rocm
#  allow_failure: true
#  variables:
#    CI_BUILD_ARGS: 'LLVM_VER=9.0.1 USE_BINARYBUILDER_LLVM=0'

# other tasks

coverage:
  extends:
    - .julia:nightly
    - .coverage

documentation:
  extends:
    - .julia:nightly
    - .documentation
  tags:
    - rocm

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
