name = "HSARuntime"
uuid = "2c364e2c-59fb-59c3-96f3-194112e690e0"
authors = ["Julian P Samaroo <jpsamaroo@jpsamaroo.me"]
version = "0.0.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
